'''
Script to fix the broken GTFs generated by bambu
'''
STRAND_field = 6

import re
import sys

def fix_gtf_line(line):
    # Check the strand field to determine if the gene is unstranded
    fields = line.strip().split('\t')
    if len(fields) > STRAND_field and fields[STRAND_field] == '.':
        # Skip unstranded genes
        return ""
    # Match the pattern in the malformed 'gene_id' field
    # Corrects lines like: gene_id "transcript_id SIRV101; SIRV1";
    match = re.search(r'gene_id "transcript_id\s\S+;\s(\S+)";', line)
    
    if match:
        correct_gene_id = match.group(1)
        corrected_line = re.sub(r'gene_id "transcript_id\s\S+;\s\S+";', f'gene_id "{correct_gene_id}";', line)
        return corrected_line
    else:
        return line

def fix_gtf_file(input_gtf, output_gtf):
    with open(input_gtf, 'r') as infile, open(output_gtf, 'w') as outfile:
        for line in infile:
            if line.startswith('#'):
                # Write header/comment lines unchanged
                outfile.write(line)
            else:
                # Fix the malformed line if necessary
                fixed_line = fix_gtf_line(line)
                if fixed_line:
                    outfile.write(fixed_line)

if __name__ == "__main__":
    # Define input and output GTF file paths
    input_gtf = sys.argv[1]
    output_gtf = sys.argv[2]
    
    # Fix the GTF file
    fix_gtf_file(input_gtf, output_gtf)

    print(f"Fixed GTF file written to {output_gtf}")
