import pandas as pd
import argparse
import pyranges as pr
import os
from collections import defaultdict

parser = argparse.ArgumentParser()
parser.add_argument('--rescue_gtf', help = 'TMs *filtered.gtf')
parser.add_argument('--rescued', help = '*rules_rescue_rescue_table.tsv')
parser.add_argument('--inclusion_list', help = '_rescue_inclusion-list.tsv generated by rescue')
parser.add_argument('--counts', help = 'Isoforms abundancy values: "Isoform" \t "Count". Column names may differ')
parser.add_argument('--counts_in_TPM', action = "store_true", help = 'Indicate if provided counts file is in TPM True/False. Default False)', required = False)
parser.add_argument('--out_dir', default = 'SQ_requant', help = 'Output directory, optional', required = False)
parser.add_argument('--out', default = 'SQ_requant', help = 'Out prefix', required = False)

print('1. Parsing arguments')
args = parser.parse_args()

rescue_gtf = pr.read_gtf(args.rescue_gtf).df
rescued = pd.read_csv(args.rescued, sep = '\t')
inclusion_list = pd.read_csv(args.inclusion_list, sep = '\t')
count_matrix = pd.read_csv(args.counts, sep = ',', comment='#')

counts_in_TPM = args.counts_in_TPM
out_dir = args.out_dir
out = args.out

os.makedirs(out_dir, exist_ok=True)

def calculate_tpm(counts, lengths):
    # Convert lengths to kilobases
    lengths_kb = lengths / 1000
    # Calculate RPK
    rpk = counts / lengths_kb
    # Calculate Total RPK
    total_rpk = rpk.sum()
    # Calculate TPM
    tpm = (rpk / total_rpk) * 1e6
    return tpm

def select_hit(isoform, rescued, new_counts, old_counts):
    group = rescued[rescued["mapping_hit"] == isoform]
    candidate_sum = 0
    if not group.empty:
        for cand in group['rescue_candidate']:
            candidate_sum += old_counts.get(cand, 0)
            new_counts[cand] = 0
    base_count = 0 if (isoform in new_counts and new_counts[isoform] == 0) else old_counts.get(isoform, 0)
    new_counts[isoform] = base_count + candidate_sum
    return new_counts

def reassign_counts(isoform, old_counts, new_counts, list_of_changed):
    if isoform in new_counts:
        count = new_counts[isoform]
        list_of_changed.append(isoform)
    else:
        try:
            count = old_counts[isoform]
        except KeyError:
            count = 0
    return(count)

def fill_old_counts(isoform, old_counts):
    try:
        count = old_counts[isoform]
    except KeyError:
        count = 0
    return(count)

#select list of isoforms that were rescued by SQANTI3 rescue
rescued_iso = rescued[rescued['rescue_result'] != 'not_rescued']
additional_isoforms = rescued[rescued['exclusion_reason'] == 'reference_already_present']
rescued = pd.concat([rescued_iso, additional_isoforms])
rescued = rescued.drop_duplicates(['rescue_candidate', 'mapping_hit'])

# Pre-calculate transcript lengths once before sample loop to avoid mutating rescue_gtf
exons = rescue_gtf[rescue_gtf['Feature'] == 'exon'].copy()
if not exons.empty:
    exons['exon_length'] = exons['End'] - exons['Start'] + 1
    transcript_lengths = exons.groupby('transcript_id')['exon_length'].sum().reset_index()
    transcript_lengths.columns = ['Transcript_ID', 'Length']
    lengths_d = transcript_lengths.set_index('Transcript_ID')['Length'].to_dict()
elif (rescue_gtf['Feature'] == 'transcript').any():
    tx_features = rescue_gtf[rescue_gtf['Feature'] == 'transcript'].copy()
    tx_features['t_length'] = tx_features['End'] - tx_features['Start'] + 1
    lengths_d = tx_features.groupby('transcript_id')['t_length'].first().to_dict()
else:
    lengths_d = {}

if (rescue_gtf['Feature'] == 'transcript').any():
    rescue_gtf_transcripts = rescue_gtf[rescue_gtf['Feature'] == 'transcript'][['transcript_id']].drop_duplicates().copy()
else:
    rescue_gtf_transcripts = pd.DataFrame({'transcript_id': rescue_gtf['transcript_id'].dropna().unique()})

rescue_gtf_transcripts['t_length'] = rescue_gtf_transcripts['transcript_id'].map(lambda x: lengths_d.get(x, 0))

original_rescued = rescued.copy()
df_list = [] 

#create dictionaries of old and new counts
for sample_idx in range(1, count_matrix.shape[1]):
    sample_name = count_matrix.columns[sample_idx]
    counts = count_matrix.iloc[:, [0, sample_idx]]
    counts.columns = ['transcript_id', 'count']
    old_counts = counts.set_index('transcript_id')['count'].to_dict()
    new_counts = defaultdict(int)

    #reassign counts to surviving isoforms using fresh copy of rescued dataframe
    sample_rescued = original_rescued[original_rescued['rescue_candidate'].isin(old_counts.keys())]
    inclusion_list.apply(lambda x: select_hit(x[0], sample_rescued, new_counts, old_counts), axis = 1)

    #combine old and new counts
    counts_df = pd.DataFrame(rescue_gtf['transcript_id'].dropna().unique(), columns = ['transcript_id'])
    counts_df['old_count'] = counts_df['transcript_id'].apply(lambda x: fill_old_counts(x, old_counts))

    list_of_changed = []
    counts_df['new_count'] = counts_df['transcript_id'].apply(lambda x: reassign_counts(x, old_counts, new_counts, list_of_changed))

    counts_df_short = counts_df[['transcript_id', 'new_count']].copy()
    counts_df_short.columns = ['transcript_id', sample_name]
    counts_df_short.set_index('transcript_id', inplace = True)
    df_list.append(counts_df_short)

    if not counts_in_TPM:
        sample_gtf = rescue_gtf_transcripts.copy()
        counts_d = counts_df_short[sample_name].to_dict()
        sample_gtf['counts'] = sample_gtf['transcript_id'].map(lambda x: counts_d.get(x, 0))
        #remove zero values
        sample_gtf = sample_gtf[sample_gtf['counts'] != 0]

        if not sample_gtf.empty:
            # Calculate TPM
            sample_gtf['TPM'] = calculate_tpm(sample_gtf['counts'], sample_gtf['t_length'])
            final = sample_gtf[['transcript_id', 'TPM']]
            final.to_csv(f"{out_dir}/{out}_{sample_name}_reassigned_counts_TPM.tsv", header = True, sep='\t', index=False)

# join all samples
if df_list:
    final_df = pd.concat(df_list, axis=1)
    final_df.to_csv(f"{out_dir}/{out}_reassigned_counts.tsv", header = True, index = True, index_label="transcript_id", sep = '\t')
