# Config file for test / dry-run execution
experiment: "test_run"
data_type: "pacbio"
output_dir: "results_test"

metadata: "test_data/test_metadata.csv"
factors: "test_data/test_factors.csv"

sr_analysis: false

reference_genome: "test_data/tiny_genome.fa"
reference_annotation: "test_data/tiny_annotation.gtf"

tools: ["kallisto", "bambu"]

sqanti_dir: "SQANTI3"
normalization_methods: ["CPM", "TPM"]
min_count_condition: 0

sirv_analysis: false
iso_per_gene_analysis: false
replicability_analysis: false
coverage_analysis: false

report_factors: ["Tissue", "Pool"]
